version: '3.9'

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/dev
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mysql
      - elasticsearch
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
    ports:
      - '3306:3306'
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - backend
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: 'unless-stopped'

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  es_data:
    driver: local
